# example/pubspec.yaml

name: smart_lib_theme_example
description: Example app for smart_lib_theme package.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  smart_lib_theme: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter