name: smart_lib_theme
description: "A new Flutter project."
version: 1.0.0

homepage: https://github.com/vanik98/smart_lib_theme
repository: https://github.com/vanik98/smart_lib_theme
issue_tracker: https://github.com/vanik98/smart_lib_theme/issues

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.2
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

